#!/usr/bin/env python3
"""Train YOLOv11-seg on SAM-derived polygon labels.

Builds a YOLO-shaped staging dir (symlinks back to data/images/ and the
chosen SAM polygon-labels dir), writes split list files derived from
analysis/splits.csv, then calls ultralytics' training loop.

Staging layout:
    yolo_dataset/
        dataset.yaml
        images/   (symlinks into data/images/)
        labels/   (symlinks into labels_seg_l/)
        train.txt val.txt test.txt   (paths relative to repo root)

This script is for training only; evaluate with scripts/eval_yolo.py and
export ONNX with scripts/export_onnx.py.

Augmentation: ultralytics defaults. Pass augmentation kwargs via the
script (a future change) only after seeing the train/val curve.
"""

from __future__ import annotations

import argparse
import csv
import os
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
FILENAME_RE = re.compile(r"^(\d+)_(\d+)\.png$")
VALID_SPLITS = ("train", "val", "test")


def rel_to_root(path: Path) -> str:
    try:
        return str(path.resolve().relative_to(REPO_ROOT))
    except ValueError:
        return str(path)


def ensure_symlink(link: Path, target: Path) -> None:
    """Create a relative symlink at `link` pointing at `target`. Idempotent."""
    rel_target = Path(os.path.relpath(target.resolve(), link.parent.resolve()))
    if link.is_symlink() or link.exists():
        if link.is_symlink() and Path(os.readlink(link)) == rel_target:
            return
        link.unlink()
    link.symlink_to(rel_target)


def load_board_splits(splits_csv: Path) -> dict[int, str]:
    """Parse analysis/splits.csv → {board: split}."""
    if not splits_csv.is_file():
        raise SystemExit(f"missing {splits_csv}; run scripts/make_splits.py first.")
    out: dict[int, str] = {}
    with splits_csv.open() as fh:
        for row in csv.DictReader(fh):
            split = row["split"].strip()
            if split not in VALID_SPLITS:
                raise SystemExit(f"unexpected split {split!r} in {splits_csv}")
            out[int(row["board"])] = split
    return out


def build_staging(args: argparse.Namespace) -> Path:
    images_dir = args.data_dir / "images"
    seg_dir = args.seg_labels_dir
    if not images_dir.is_dir():
        raise SystemExit(f"{images_dir} not found.")
    if not seg_dir.is_dir():
        raise SystemExit(f"{seg_dir} not found.")

    board_to_split = load_board_splits(args.splits_csv)

    args.staging_dir.mkdir(parents=True, exist_ok=True)
    images_link_dir = args.staging_dir / "images"
    labels_link_dir = args.staging_dir / "labels"
    images_link_dir.mkdir(exist_ok=True)
    labels_link_dir.mkdir(exist_ok=True)

    by_split: dict[str, list[str]] = {s: [] for s in VALID_SPLITS}
    n_paired = 0
    n_no_label = 0
    n_no_split = 0
    for img_path in sorted(images_dir.glob("*.png")):
        m = FILENAME_RE.match(img_path.name)
        if not m:
            continue
        board = int(m.group(1))
        split = board_to_split.get(board)
        if split is None:
            n_no_split += 1
            continue

        lbl_path = seg_dir / f"{img_path.stem}.txt"
        if not lbl_path.exists():
            n_no_label += 1
            continue

        ensure_symlink(images_link_dir / img_path.name, img_path)
        ensure_symlink(labels_link_dir / lbl_path.name, lbl_path)
        # Path relative to repo root (= cwd in our Docker setup).
        by_split[split].append(str(images_link_dir.relative_to(REPO_ROOT) / img_path.name))
        n_paired += 1

    for split in VALID_SPLITS:
        (args.staging_dir / f"{split}.txt").write_text("\n".join(by_split[split]) + "\n")

    yaml_path = args.staging_dir / "dataset.yaml"
    yaml_path.write_text(
        "# Auto-generated by scripts/train_yolo.py — do not commit.\n"
        "# Paths are relative to cwd (repo root in our Docker setup).\n"
        "train: train.txt\n"
        "val: val.txt\n"
        "test: test.txt\n"
        "names:\n"
        "  0: knot\n"
    )

    print(f"staging at {rel_to_root(args.staging_dir)}/")
    print(f"  paired (image, label) symlinks: {n_paired}")
    if n_no_label:
        print(f"  WARN: {n_no_label} frame(s) missing in {rel_to_root(seg_dir)}/ — skipped")
    if n_no_split:
        print(f"  WARN: {n_no_split} frame(s) whose board is not in splits.csv — skipped")
    print(
        f"  train={len(by_split['train'])}  val={len(by_split['val'])}  test={len(by_split['test'])}"
    )
    return yaml_path


def main() -> None:
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.add_argument(
        "--data-dir",
        type=Path,
        default=REPO_ROOT / "data",
        help="Read-only input root containing images/.",
    )
    ap.add_argument(
        "--seg-labels-dir",
        type=Path,
        default=REPO_ROOT / "labels_seg_l",
        help="SAM polygon labels (YOLO-seg format).",
    )
    ap.add_argument(
        "--splits-csv",
        type=Path,
        default=REPO_ROOT / "analysis" / "splits.csv",
        help="Board-level split assignment from make_splits.py.",
    )
    ap.add_argument(
        "--staging-dir",
        type=Path,
        default=REPO_ROOT / "yolo_dataset",
        help="Where the YOLO scaffold (symlinks + dataset.yaml) lives.",
    )
    ap.add_argument(
        "--model", default="yolo11m-seg.pt", help="Starting checkpoint or model variant."
    )
    ap.add_argument("--epochs", type=int, default=100)
    ap.add_argument("--imgsz", type=int, default=640)
    ap.add_argument("--batch", type=int, default=16)
    ap.add_argument("--patience", type=int, default=20)
    ap.add_argument("--name", default="train", help="Run name (suffix in runs/segment/).")
    ap.add_argument(
        "--project",
        type=Path,
        default=None,
        help="Output project dir; default = ultralytics' runs/segment/.",
    )
    ap.add_argument("--device", default="0")
    ap.add_argument("--workers", type=int, default=8)
    ap.add_argument(
        "--resume", action="store_true", help="Resume the last checkpoint of this run name."
    )
    ap.add_argument(
        "--setup-only", action="store_true", help="Build the staging dir and exit (no training)."
    )
    args = ap.parse_args()

    yaml_path = build_staging(args)
    if args.setup_only:
        print("--setup-only: skipping training")
        return

    from ultralytics import YOLO

    print(f"loading {args.model} …")
    model = YOLO(args.model)

    print(
        f"training: epochs={args.epochs}  imgsz={args.imgsz}  "
        f"batch={args.batch}  patience={args.patience}  device={args.device}"
    )
    train_kwargs = dict(
        data=str(yaml_path),
        epochs=args.epochs,
        imgsz=args.imgsz,
        batch=args.batch,
        patience=args.patience,
        name=args.name,
        device=args.device,
        workers=args.workers,
        resume=args.resume,
    )
    if args.project is not None:
        train_kwargs["project"] = str(args.project)
    model.train(**train_kwargs)
    print("\nbest weights:", model.trainer.best)


if __name__ == "__main__":
    main()
